// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CapY89qKhO_dff7q4ZUUbyShL7CGn7E',
    appId: '1:510981508664:web:b57e94bfeed0eb241060cd',
    messagingSenderId: '510981508664',
    projectId: 'medical-profile-961f1',
    authDomain: 'medical-profile-961f1.firebaseapp.com',
    storageBucket: 'medical-profile-961f1.firebasestorage.app',
    measurementId: 'G-38JQ7P2NSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGnKNB7qEQj3XAe2tNkL_Yo0z9Qk8G44',
    appId: '1:510981508664:android:a37f6d659fab0c801060cd',
    messagingSenderId: '510981508664',
    projectId: 'medical-profile-961f1',
    storageBucket: 'medical-profile-961f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCh3ZfipHs9IhB-N7Hh7sGBG08STW1II',
    appId: '1:510981508664:ios:7687ed762967e4371060cd',
    messagingSenderId: '510981508664',
    projectId: 'medical-profile-961f1',
    storageBucket: 'medical-profile-961f1.firebasestorage.app',
    iosBundleId: 'com.nastya.medicalprofile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCh3ZfipHs9IhB-N7Hh7sGBG08STW1II',
    appId: '1:510981508664:ios:6d6d51482bdc5ffc1060cd',
    messagingSenderId: '510981508664',
    projectId: 'medical-profile-961f1',
    storageBucket: 'medical-profile-961f1.firebasestorage.app',
    iosBundleId: 'com.example.medicalProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4CapY89qKhO_dff7q4ZUUbyShL7CGn7E',
    appId: '1:510981508664:web:6976e7075cd732d81060cd',
    messagingSenderId: '510981508664',
    projectId: 'medical-profile-961f1',
    authDomain: 'medical-profile-961f1.firebaseapp.com',
    storageBucket: 'medical-profile-961f1.firebasestorage.app',
    measurementId: 'G-30KGFG0ESY',
  );
}
